# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Script - ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install npm
      run: npm install
    - name: Install dependencies
      run: npm ci
    - name: Run ci-on_pr_main script
      run: |
         chmod +x ./scripts/ci-on_pr_main.sh
         ./scripts/ci-on_pr_main.sh
      shell: bash